#!/bin/bash

export DND_PRE_ROLL="${DND_PRE_ROLL:-0.30}"
export DND_POST_ROLL="${DND_POST_ROLL:-0.40}"
export DND_MIN_REMOVE_DURATION="${DND_MIN_REMOVE_DURATION:-0.80}"
export DND_MIN_SPEECH_DURATION="${DND_MIN_SPEECH_DURATION:-0.25}"
export DND_SPEECH_KEEP_THRESHOLD="${DND_SPEECH_KEEP_THRESHOLD:-0.40}"
export DND_SPEECH_REVIEW_THRESHOLD="${DND_SPEECH_REVIEW_THRESHOLD:-0.50}"

export DND_WHISPER_MODEL="${DND_WHISPER_MODEL:-small}"
export DND_WHISPER_LANGUAGE="${DND_WHISPER_LANGUAGE:-en}"
export DND_WHISPER_DEVICE="${DND_WHISPER_DEVICE:-cuda}"

export DND_AUDIO_PLAYER="${DND_AUDIO_PLAYER:-ffplay -hide_banner -loglevel error -autoexit -nodisp}"

export DND_AUTO_RESUME="${DND_AUTO_RESUME:-ask}"

export DND_NO_PAUSE="${DND_NO_PAUSE:-0}"

export BASH_ALIASES_VENV_BIN="${BASH_ALIASES_VENV_BIN:-$HOME/.bash_aliases_scripts/.venv/bin}"

export DND_LOG_FILE="${DND_LOG_FILE:-}"
export DND_ERROR_LOG="${DND_ERROR_LOG:-}"

export DND_QUIT_REQUESTED="${DND_QUIT_REQUESTED:-0}"
