#!/bin/bash

export DND_PRE_ROLL="${DND_PRE_ROLL:-0.30}"
export DND_POST_ROLL="${DND_POST_ROLL:-0.40}"
export DND_MIN_REMOVE_DURATION="${DND_MIN_REMOVE_DURATION:-0.80}"
export DND_MIN_SPEECH_DURATION="${DND_MIN_SPEECH_DURATION:-0.25}"
export DND_SPEECH_KEEP_THRESHOLD="${DND_SPEECH_KEEP_THRESHOLD:-0.40}"
export DND_SPEECH_REVIEW_THRESHOLD="${DND_SPEECH_REVIEW_THRESHOLD:-0.50}"

export DND_WHISPER_MODEL="${DND_WHISPER_MODEL:-small}"
export DND_WHISPER_LANGUAGE="${DND_WHISPER_LANGUAGE:-}"
export DND_WHISPER_DEVICE="${DND_WHISPER_DEVICE:-cuda}"

export DND_AUTO_RESUME="${DND_AUTO_RESUME:-ask}"

export DND_NO_PAUSE="${DND_NO_PAUSE:-0}"

export BASH_ALIASES_VENV_BIN="${BASH_ALIASES_VENV_BIN:-$HOME/.bash_aliases_scripts/.venv/bin}"

export DND_LOG_FILE="${DND_LOG_FILE:-}"
export DND_ERROR_LOG="${DND_ERROR_LOG:-}"

export DND_QUIT_REQUESTED="${DND_QUIT_REQUESTED:-0}"

export DND_SNAP_WINDOW_S="${DND_SNAP_WINDOW_S:-0.5}"
export DND_AUDIO_SNAP_WINDOW_S="${DND_AUDIO_SNAP_WINDOW_S:-0.2}"

export DND_RENDER_MODE="${DND_RENDER_MODE:-auto}"
export DND_RENDER_THREADS="${DND_RENDER_THREADS:-}"
export DND_VIDEO_CRF="${DND_VIDEO_CRF:-18}"
export DND_AUDIO_BITRATE="${DND_AUDIO_BITRATE:-192k}"

export DND_KEEP_SEGMENTS="${DND_KEEP_SEGMENTS:-1}"